import {FormEvent, ReactNode, useEffect, useState} from "react";
import {Link, Navigate, Route, Routes, useNavigate} from "react-router-dom";
import {useMutation, useQuery, useQueryClient} from "@tanstack/react-query";
import {api, ApiError, Connection, LinkRequest, Session, setCsrf} from "./api";

function Shell({children}: {children: ReactNode}) {return <main className="min-h-screen"><header className="mx-auto flex max-w-6xl items-center justify-between px-6 py-7"><Link to="/" className="font-black tracking-tight text-xl">JIM<span className="rounded bg-lime px-1">007</span></Link><span className="text-sm text-moss">Train. Track. Improve.</span></header>{children}</main>}
function Message({error}: {error: unknown}) {if (!error) return null; return <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{error instanceof ApiError ? error.message : "Something went wrong. Please try again."}</p>}
function AuthCard({title, subtitle, children}: {title: string; subtitle: string; children: ReactNode}) {return <Shell><section className="mx-auto grid max-w-6xl gap-10 px-6 pb-14 pt-8 lg:grid-cols-[1.1fr_.9fr]"><div className="pt-8"><p className="eyebrow">Your training, your data</p><h1 className="mt-4 max-w-xl text-5xl font-extrabold leading-[1.02] sm:text-7xl">A workout journal built around you.</h1><p className="mt-6 max-w-lg text-lg text-moss">Track your workouts, follow your progress, and keep your training data in one place.</p></div><div className="card"><h2 className="text-3xl font-bold">{title}</h2><p className="mb-7 mt-2 text-moss">{subtitle}</p>{children}</div></section></Shell>}
function Password({value, onChange, label = "Password"}: {value: string; onChange: (value: string) => void; label?: string}) {return <label className="block"><span className="label">{label}</span><input type="password" autoComplete="current-password" minLength={12} maxLength={128} required value={value} onChange={event => onChange(event.target.value)}/><span className="mt-1 block text-xs text-moss">12 to 128 characters.</span></label>}

function Register() {const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const mutation=useMutation({mutationFn:()=>api<void>("/api/auth/register",{method:"POST",body:JSON.stringify({email,password})})}); const submit=(event:FormEvent)=>{event.preventDefault();mutation.mutate()}; return <AuthCard title="Create your account" subtitle="Start tracking your training with JIM007.">{mutation.isSuccess?<div className="rounded-2xl bg-lime/30 p-5"><b>Check your email.</b><p className="mt-1 text-sm">Open the verification link to continue.</p></div>:<form onSubmit={submit} className="space-y-5"><label className="block"><span className="label">Email</span><input type="email" autoComplete="email" required value={email} onChange={event=>setEmail(event.target.value)}/></label><Password value={password} onChange={setPassword}/><Message error={mutation.error}/><button className="button w-full" disabled={mutation.isPending}>Create account</button></form>}<p className="mt-6 text-sm text-moss">Already have an account? <Link className="font-bold underline" to="/login">Sign in</Link></p></AuthCard>}
function Login() {const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const navigate=useNavigate(); const queryClient=useQueryClient(); const mutation=useMutation({mutationFn:()=>api<void>("/api/auth/login",{method:"POST",body:JSON.stringify({email,password})}),onSuccess:async()=>{setCsrf(null);await queryClient.clear();navigate("/account")}}); return <AuthCard title="Welcome back" subtitle="Sign in to your workout account."><form onSubmit={event=>{event.preventDefault();mutation.mutate()}} className="space-y-5"><label className="block"><span className="label">Email</span><input type="email" autoComplete="email" required value={email} onChange={event=>setEmail(event.target.value)}/></label><Password value={password} onChange={setPassword}/><Message error={mutation.error}/><button className="button w-full" disabled={mutation.isPending}>Sign in</button></form><div className="mt-6 flex justify-between text-sm"><Link className="font-bold underline" to="/register">Create account</Link><Link className="font-bold underline" to="/forgot-password">Forgot password?</Link></div></AuthCard>}
function TokenPage({purpose}:{purpose:"verify"|"reset"}) {const token=new URLSearchParams(location.hash.slice(1)).get("token")??""; const [password,setPassword]=useState(""); const navigate=useNavigate(); const mutation=useMutation({mutationFn:()=>api<void>(purpose==="verify"?"/api/auth/verify-email":"/api/auth/reset-password",{method:"POST",body:JSON.stringify(purpose==="verify"?{token}:{token,new_password:password})}),onSuccess:()=>{history.replaceState(null,"",location.pathname);navigate("/account")}}); return <AuthCard title={purpose==="verify"?"Verify your email":"Choose a new password"} subtitle="Your token is used only when you confirm.">{!token?<Message error={new Error()}/>:<form onSubmit={event=>{event.preventDefault();mutation.mutate()}} className="space-y-5">{purpose==="reset"&&<Password label="New password" value={password} onChange={setPassword}/>}<Message error={mutation.error}/><button className="button w-full" disabled={mutation.isPending}>{purpose==="verify"?"Verify and continue":"Save new password"}</button></form>}</AuthCard>}
function EmailAction({kind}:{kind:"forgot"|"resend"}) {const [email,setEmail]=useState(""); const mutation=useMutation({mutationFn:()=>api<void>(kind==="forgot"?"/api/auth/forgot-password":"/api/auth/resend-verification",{method:"POST",body:JSON.stringify({email})})}); return <AuthCard title={kind==="forgot"?"Reset your password":"Resend verification email"} subtitle="If the address belongs to an account, we will send you an email."><form onSubmit={event=>{event.preventDefault();mutation.mutate()}} className="space-y-5"><label className="block"><span className="label">Email</span><input type="email" required value={email} onChange={event=>setEmail(event.target.value)}/></label><Message error={mutation.error}/>{mutation.isSuccess&&<p className="rounded-xl bg-lime/30 p-3">Check your inbox.</p>}<button className="button w-full">Send email</button></form></AuthCard>}

function Account() {
  const queryClient=useQueryClient(); const navigate=useNavigate();
  const session=useQuery({queryKey:["session"],queryFn:async()=>{const value=await api<Session>("/api/auth/session");setCsrf(value.csrf_token);return value},retry:false});
  const connection=useQuery({queryKey:["telegram-connection"],queryFn:()=>api<Connection>("/api/me/telegram-connection"),enabled:session.isSuccess});
  const [request,setRequest]=useState<LinkRequest|null>(null); const [password,setPassword]=useState("");
  const status=useQuery({queryKey:["link-request",request?.id],queryFn:()=>api<LinkRequest>(`/api/me/telegram-link-requests/${request!.id}`),enabled:!!request&&! ["completed","cancelled","expired"].includes(request.status),refetchInterval:query=>query.state.data?.status==="pending_web_confirmation"?false:2500});
  useEffect(()=>{if(status.data)setRequest(old=>({...old,...status.data} as LinkRequest))},[status.data]);
  useEffect(()=>{const focus=()=>{void status.refetch()};window.addEventListener("focus",focus);return()=>window.removeEventListener("focus",focus)},[status]);
  const create=useMutation({mutationFn:()=>api<LinkRequest>("/api/me/telegram-link-requests",{method:"POST",body:"{}"}),onSuccess:value=>{setRequest(value);window.open(value.deep_link??"","_blank","noopener,noreferrer")}});
  const confirm=useMutation({mutationFn:()=>api<Connection>(`/api/me/telegram-link-requests/${request!.id}/confirm`,{method:"POST",body:"{}"}),onSuccess:async()=>{setRequest(null);await connection.refetch()}});
  const cancel=useMutation({mutationFn:()=>api<void>(`/api/me/telegram-link-requests/${request!.id}`,{method:"DELETE",body:"{}"}),onSuccess:()=>setRequest(null)});
  const unlink=useMutation({mutationFn:()=>api<void>("/api/me/telegram-connection/unlink",{method:"POST",body:JSON.stringify({password})}),onSuccess:async()=>{setPassword("");await connection.refetch()}});
  const logout=useMutation({mutationFn:()=>api<void>("/api/auth/logout",{method:"POST",body:"{}"}),onSuccess:async()=>{setCsrf(null);queryClient.clear();navigate("/login")}});
  if(session.isLoading)return <Shell><p className="p-10">Loading…</p></Shell>;
  if(session.error instanceof ApiError&&session.error.status===401)return <Navigate to="/login" replace/>;
  const candidate=request?.candidate;
  return <Shell><section className="mx-auto max-w-5xl px-6 pb-16 pt-8">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Your space</p><h1 className="mt-2 text-5xl font-extrabold">Your account</h1><p className="mt-2 text-moss">Manage your profile and connected services.</p></div><button className="button-secondary" onClick={()=>logout.mutate()}>Sign out</button></div>
    <div className="mt-10 grid gap-6 md:grid-cols-[1fr_1.4fr]">
      <article className="card"><p className="eyebrow">Account</p><h2 className="mt-3 text-2xl font-bold">Profile</h2><p className="mt-2 break-all text-moss">{session.data?.email}</p><span className="mt-6 inline-flex rounded-full bg-lime/40 px-3 py-1 text-sm font-bold">Email verified</span></article>
      <article className="card"><p className="eyebrow">Integrations</p><h2 className="mt-3 text-2xl font-bold">Telegram</h2>
      {connection.data?.linked?<><p className="mt-2 text-moss">Connected as {connection.data.display_name||"Telegram user"}{connection.data.username&&` · @${connection.data.username}`}</p><p className="mt-4 text-sm text-moss">Log and review workouts directly from Telegram.</p><div className="mt-6 space-y-3"><Password value={password} onChange={setPassword}/><Message error={unlink.error}/><button className="button-secondary w-full" disabled={password.length<12||unlink.isPending} onClick={()=>unlink.mutate()}>Disconnect Telegram</button></div></>:<><p className="mt-2 text-moss">Connect Telegram to log workouts from chat.</p>{!request&&<button className="button-secondary mt-6 w-full" disabled={create.isPending} onClick={()=>create.mutate()}>Connect Telegram</button>}<Message error={create.error||confirm.error||cancel.error}/>{request&&<div className="mt-6 rounded-2xl bg-cream p-4"><p className="text-sm font-bold">{request.status==="pending_telegram"?"Waiting for you to open Telegram…":request.status==="pending_web_confirmation"?"Confirm the Telegram profile below":"This request is no longer valid"}</p>{candidate&&<p className="mt-2">{candidate.display_name??"Telegram profile"}{candidate.username&&` · @${candidate.username}`}</p>}<div className="mt-4 flex gap-2">{request.status==="pending_telegram"&&request.deep_link&&<a className="button flex-1" href={request.deep_link} target="_blank" rel="noreferrer">Open Telegram</a>}{request.status==="pending_web_confirmation"&&<button className="button flex-1" onClick={()=>confirm.mutate()}>Confirm</button>}<button className="button-secondary" onClick={()=>cancel.mutate()}>Cancel</button></div></div>}</>}</article>
    </div>
  </section></Shell>;
}

export function App(){return <Routes><Route path="/" element={<Navigate to="/account" replace/>}/><Route path="/register" element={<Register/>}/><Route path="/login" element={<Login/>}/><Route path="/verify-email" element={<TokenPage purpose="verify"/>}/><Route path="/forgot-password" element={<EmailAction kind="forgot"/>}/><Route path="/reset-password" element={<TokenPage purpose="reset"/>}/><Route path="/account" element={<Account/>}/><Route path="*" element={<Navigate to="/account" replace/>}/></Routes>}
