import {FormEvent, ReactNode, useMemo, useState} from "react";
import {NavLink, useParams} from "react-router-dom";
import {useInfiniteQuery, useMutation, useQuery, useQueryClient} from "@tanstack/react-query";
import {
  Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer,
  Tooltip, XAxis, YAxis,
} from "recharts";
import {
  ApiError, ExerciseCatalog, ExerciseStatistics, historyApi, MassMetric, OverviewStatistics,
  StatisticsPeriod, VolumeMetric, Workout, WorkoutExercise,
} from "./api";

const dateFormat = new Intl.DateTimeFormat("en-GB", {day: "numeric", month: "long", year: "numeric"});
const shortDateFormat = new Intl.DateTimeFormat("en-GB", {day: "numeric", month: "short"});
const periods: Array<[StatisticsPeriod, string]> = [["4w", "4 weeks"], ["12w", "12 weeks"], ["1y", "1 year"], ["all", "All"]];

function parseDate(value: string) {const parts=value.split("-");return new Date(Number(parts[0]),Number(parts[1])-1,Number(parts[2]))}
function formatDate(value: string) {return dateFormat.format(parseDate(value))}
function formatShortDate(value: string) {return shortDateFormat.format(parseDate(value))}
function compactNumber(value: number) {return value.toLocaleString("en-GB", {maximumFractionDigits: 1})}
function formatLoad(value: string, unit: string) {return `${Number(value).toLocaleString("en-GB", {maximumFractionDigits: 3})} ${unit}`}
function formatMass(value: MassMetric | null) {return value?formatLoad(value.value,value.unit):"—"}
function formatVolume(value: VolumeMetric | null) {return value?`${compactNumber(Number(value.value))} ${value.load_unit} · reps`:"—"}

export function AppShell({children}: {children: ReactNode}) {
  const links = [["/", "Dashboard"], ["/workouts", "Workouts"], ["/exercises", "Exercises"], ["/account", "Account"]] as const;
  return <main className="min-h-screen"><header className="border-b border-ink/10 bg-white/70 backdrop-blur"><div className="mx-auto flex max-w-6xl flex-wrap items-center gap-x-8 gap-y-4 px-6 py-5"><NavLink to="/" className="mr-auto font-black tracking-tight text-xl">JIM<span className="rounded bg-lime px-1">007</span></NavLink><nav aria-label="Main navigation" className="order-3 flex w-full gap-1 overflow-x-auto sm:order-none sm:w-auto">{links.map(([to,label])=><NavLink key={to} to={to} end={to==="/"} className={({isActive})=>`rounded-xl px-3 py-2 text-sm font-bold ${isActive?"bg-ink text-white":"text-moss hover:bg-cream hover:text-ink"}`}>{label}</NavLink>)}</nav><span className="hidden text-sm text-moss lg:block">Train. Track. Improve.</span></div></header>{children}</main>;
}

function PageHeader({eyebrow,title,description}: {eyebrow:string;title:string;description:string}) {return <div><p className="eyebrow">{eyebrow}</p><h1 className="mt-2 text-4xl font-extrabold sm:text-5xl">{title}</h1><p className="mt-3 max-w-2xl text-moss">{description}</p></div>}
function QueryError({error,retry}: {error:unknown;retry:()=>void}) {const message=error instanceof ApiError?error.message:"We could not load this section.";return <div role="alert" className="card"><h2 className="text-xl font-bold">Something went wrong</h2><p className="mt-2 text-moss">{message}</p><button className="button-secondary mt-5" onClick={retry}>Try again</button></div>}
function LoadingCards() {return <div aria-label="Loading" className="grid gap-4"><div className="card h-36 animate-pulse bg-white/70"/><div className="card h-36 animate-pulse bg-white/70"/></div>}

function PeriodSelector({value,onChange}: {value:StatisticsPeriod;onChange:(value:StatisticsPeriod)=>void}) {return <div className="inline-flex flex-wrap gap-1 rounded-2xl border border-ink/10 bg-white p-1" aria-label="Statistics period">{periods.map(([key,label])=><button key={key} type="button" aria-pressed={value===key} className={`rounded-xl px-3 py-2 text-sm font-bold ${value===key?"bg-ink text-white":"text-moss hover:bg-cream"}`} onClick={()=>onChange(key)}>{label}</button>)}</div>}

function Sets({occurrence}: {occurrence:WorkoutExercise}) {return <div className="mt-3 overflow-hidden rounded-2xl border border-ink/10"><div className="grid grid-cols-[3rem_1fr_1fr] bg-cream px-4 py-2 text-xs font-bold uppercase tracking-wider text-moss"><span>Set</span><span>Load</span><span>Reps</span></div>{occurrence.sets.map(set=><div key={set.id} className="grid grid-cols-[3rem_1fr_1fr] border-t border-ink/10 px-4 py-3 text-sm"><span className="text-moss">{set.set_number}</span><span>{set.load?formatLoad(set.load.value,set.load.unit):"Bodyweight"}</span><span>{set.repetitions}</span>{set.notes&&<p className="col-span-3 mt-2 text-xs text-moss">{set.notes}</p>}</div>)}</div>}

export function WorkoutCard({workout,defaultOpen=false}: {workout:Workout;defaultOpen?:boolean}) {
  const [open,setOpen]=useState(defaultOpen);
  return <article className="card"><button className="w-full text-left" aria-expanded={open} onClick={()=>setOpen(value=>!value)}><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">{formatDate(workout.performed_on)}</p><h2 className="mt-2 text-2xl font-bold">{workout.program_workout?.alias||"Workout"}</h2></div><span className="rounded-full bg-cream px-3 py-1 text-sm font-bold">{workout.exercises.length} exercise{workout.exercises.length===1?"":"s"}</span></div>{workout.notes&&<p className="mt-3 text-sm text-moss">{workout.notes}</p>}<p className="mt-4 text-sm text-moss">{workout.exercises.map(item=>item.exercise.name).join(" · ")}</p><span className="mt-4 inline-block text-sm font-bold underline">{open?"Hide details":"View details"}</span></button>{open&&<div className="mt-6 space-y-6 border-t border-ink/10 pt-6">{workout.exercises.map(item=><section key={item.id}><div className="flex flex-wrap items-center justify-between gap-2"><NavLink className="text-lg font-bold underline decoration-lime decoration-4 underline-offset-4" to={`/exercises/${item.exercise.id}`}>{item.exercise.name}</NavLink><span className="text-sm text-moss">{item.sets.length} set{item.sets.length===1?"":"s"}</span></div>{item.notes&&<p className="mt-2 text-sm text-moss">{item.notes}</p>}<Sets occurrence={item}/></section>)}</div>}</article>;
}

function deltaLabel(current:number,previous:number|undefined) {if(previous===undefined)return null;if(previous===0)return current>0?"New":null;const delta=Math.round(((current-previous)/previous)*100);return `${delta>0?"+":""}${delta}%`}
function MetricCard({label,value,delta}: {label:string;value:string;delta?:string|null}) {return <article className="card"><p className="eyebrow">{label}</p><div className="mt-3 flex items-baseline justify-between gap-3"><p className="text-3xl font-extrabold">{value}</p>{delta&&<span className={`rounded-full px-2 py-1 text-xs font-bold ${delta.startsWith("-")?"bg-red-50 text-red-800":"bg-lime/40 text-ink"}`}>{delta}</span>}</div></article>}

function DashboardStatistics({data}: {data:OverviewStatistics}) {
  const [metric,setMetric]=useState<"workout_count"|"set_count"|"volume">("workout_count");
  const previous=data.previous;
  const chartData=data.series.map(item=>({date:formatShortDate(item.period_start),workouts:item.workout_count,sets:item.set_count,volume:item.external_volume?Number(item.external_volume.value):0}));
  const dataKey=metric==="workout_count"?"workouts":metric==="set_count"?"sets":"volume";
  const label=metric==="workout_count"?"Workouts":metric==="set_count"?"Sets":`Volume (${data.current.external_volume?.load_unit??"kg"} · reps)`;
  return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="Workouts" value={String(data.current.workout_count)} delta={deltaLabel(data.current.workout_count,previous?.workout_count)}/><MetricCard label="Active days" value={String(data.current.active_day_count)} delta={deltaLabel(data.current.active_day_count,previous?.active_day_count)}/><MetricCard label="Sets" value={data.current.set_count.toLocaleString("en-GB")} delta={deltaLabel(data.current.set_count,previous?.set_count)}/><MetricCard label="Volume" value={formatVolume(data.current.external_volume)} delta={deltaLabel(Number(data.current.external_volume?.value??0),previous?Number(previous.external_volume?.value??0):undefined)}/></div>
  <article className="card"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Training trend</p><h2 className="mt-1 text-2xl font-bold">{label}</h2></div><div className="flex gap-1 rounded-xl bg-cream p-1">{[["workout_count","Workouts"],["set_count","Sets"],["volume","Volume"]].map(([key,text])=><button key={key} className={`rounded-lg px-3 py-2 text-xs font-bold ${metric===key?"bg-white shadow":"text-moss"}`} onClick={()=>setMetric(key as typeof metric)}>{text}</button>)}</div></div><div className="mt-6 h-72" role="img" aria-label={`${label} over time`}><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey={dataKey} name={label} fill="#25342d" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div><ul className="sr-only">{chartData.map(item=><li key={item.date}>{item.date}: {item[dataKey]}</li>)}</ul></article>
  <div className="grid gap-6 lg:grid-cols-2"><article className="card"><p className="eyebrow">Most trained</p><h2 className="mt-1 text-2xl font-bold">Top exercises</h2>{data.top_exercises.length?<ol className="mt-5 space-y-3">{data.top_exercises.map((item,index)=><li key={item.exercise_id} className="flex items-center gap-3 border-b border-ink/10 pb-3"><span className="text-sm font-black text-moss">{index+1}</span><NavLink className="flex-1 font-bold underline decoration-lime decoration-4 underline-offset-4" to={`/exercises/${item.exercise_id}`}>{item.exercise_name}</NavLink><span className="text-sm text-moss">{item.workout_count} sessions</span></li>)}</ol>:<p className="mt-5 text-moss">No exercises in this period.</p>}</article><article className="card"><p className="eyebrow">Progress</p><h2 className="mt-1 text-2xl font-bold">Recent records</h2>{data.recent_records.length?<ul className="mt-5 space-y-3">{data.recent_records.map(item=><li key={`${item.workout_id}-${item.exercise_id}`} className="border-b border-ink/10 pb-3"><div className="flex justify-between gap-3"><NavLink className="font-bold underline decoration-lime decoration-4 underline-offset-4" to={`/exercises/${item.exercise_id}`}>{item.exercise_name}</NavLink><span className="font-bold">{formatMass(item.estimated_one_rep_max)}</span></div><p className="mt-1 text-sm text-moss">Estimated 1RM · {formatDate(item.performed_on)} · previous {formatMass(item.previous_best)}</p></li>)}</ul>:<p className="mt-5 text-moss">No new estimated 1RM records in this period.</p>}</article></div></div>;
}

export function DashboardPage() {
  const [period,setPeriod]=useState<StatisticsPeriod>("4w");
  const stats=useQuery({queryKey:["statistics","overview",period],queryFn:()=>historyApi.overviewStatistics(period)});
  const recent=useQuery({queryKey:["workouts","recent",3],queryFn:()=>historyApi.workouts(3)});
  return <section className="mx-auto max-w-6xl px-6 py-10"><div className="flex flex-wrap items-end justify-between gap-5"><PageHeader eyebrow="Overview" title="Dashboard" description="Your training activity, consistency, and progress at a glance."/><PeriodSelector value={period} onChange={setPeriod}/></div><div className="mt-10">{stats.isLoading?<LoadingCards/>:stats.error?<QueryError error={stats.error} retry={()=>void stats.refetch()}/>:stats.data&&<DashboardStatistics data={stats.data}/>}</div><div className="mt-12"><div className="mb-5 flex items-end justify-between"><div><p className="eyebrow">Recent activity</p><h2 className="mt-1 text-2xl font-bold">Latest workouts</h2></div><NavLink className="text-sm font-bold underline" to="/workouts">View all workouts</NavLink></div>{recent.isLoading?<LoadingCards/>:recent.error?<QueryError error={recent.error} retry={()=>void recent.refetch()}/>:recent.data?.items.length===0?<div className="card text-center"><h2 className="text-2xl font-bold">No completed workouts yet</h2><p className="mt-2 text-moss">Completed workouts will appear here.</p></div>:<div className="grid gap-5">{recent.data?.items.map((workout,index)=><WorkoutCard key={workout.id} workout={workout} defaultOpen={index===0}/>)}</div>}</div></section>;
}

export function WorkoutsPage() {
  const query=useInfiniteQuery({queryKey:["workouts",10],queryFn:({pageParam})=>historyApi.workouts(10,pageParam),initialPageParam:undefined as string|undefined,getNextPageParam:last=>last.next_cursor??undefined});
  const items=query.data?.pages.flatMap(page=>page.items)??[];
  return <section className="mx-auto max-w-4xl px-6 py-10"><PageHeader eyebrow="Training log" title="Workouts" description="Browse every completed workout and expand it to inspect exercises and sets."/><div className="mt-10">{query.isLoading?<LoadingCards/>:query.error?<QueryError error={query.error} retry={()=>void query.refetch()}/>:items.length===0?<div className="card text-center"><h2 className="text-2xl font-bold">No workouts found</h2><p className="mt-2 text-moss">Your completed workouts will appear here.</p></div>:<div className="grid gap-5">{items.map(workout=><WorkoutCard key={workout.id} workout={workout}/>)}{query.hasNextPage&&<button className="button-secondary mx-auto mt-2" disabled={query.isFetchingNextPage} onClick={()=>void query.fetchNextPage()}>{query.isFetchingNextPage?"Loading…":"Load more"}</button>}</div>}</div></section>;
}

export function ExercisesPage() {
  const queryClient=useQueryClient();const [search,setSearch]=useState("");const [formOpen,setFormOpen]=useState(false);const [name,setName]=useState("");const [notice,setNotice]=useState("");
  const query=useQuery({queryKey:["exercises"],queryFn:historyApi.exercises});
  const creation=useMutation({mutationFn:()=>historyApi.createExercise(name),onSuccess:result=>{queryClient.setQueryData<ExerciseCatalog>(["exercises"],current=>{const items=[...(current?.items??[]).filter(item=>item.id!==result.exercise.id),result.exercise];items.sort((left,right)=>left.name.localeCompare(right.name,"en",{sensitivity:"base"}));return {items}});setName("");setSearch("");setFormOpen(false);setNotice(result.created?"Exercise added to your library.":"That exercise is already in your library.")}});
  const openForm=()=>{creation.reset();setNotice("");setFormOpen(true)};
  const cancelForm=()=>{creation.reset();setName("");setFormOpen(false)};
  const submit=(event:FormEvent)=>{event.preventDefault();if(name.trim()&&!creation.isPending)creation.mutate()};
  const items=useMemo(()=>{const term=search.trim().toLocaleLowerCase();return (query.data?.items??[]).filter(item=>item.name.toLocaleLowerCase().includes(term))},[query.data,search]);
  return <section className="mx-auto max-w-5xl px-6 py-10"><div className="flex flex-wrap items-end justify-between gap-5"><PageHeader eyebrow="Exercise library" title="Exercises" description="Find an exercise and review its complete training history."/>{!formOpen&&<button className="button" type="button" onClick={openForm}>Add exercise</button>}</div>{formOpen&&<form className="card mt-8" onSubmit={submit}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="eyebrow">New exercise</p><h2 className="mt-1 text-2xl font-bold">Add to your library</h2></div><button className="text-sm font-bold underline" type="button" disabled={creation.isPending} onClick={cancelForm}>Cancel</button></div><label className="label mt-5" htmlFor="exercise-name">Exercise name</label><input id="exercise-name" aria-describedby="exercise-name-help" autoFocus required maxLength={255} placeholder="e.g. Bench Press" value={name} onChange={event=>setName(event.target.value)}/><span id="exercise-name-help" className="mt-1 block text-xs text-moss">Use a clear, recognisable name.</span>{creation.error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-800">{creation.error instanceof ApiError?creation.error.message:"We could not add this exercise. Please try again."}</p>}<button className="button mt-5" disabled={!name.trim()||creation.isPending}>{creation.isPending?"Saving…":"Save exercise"}</button></form>}{notice&&<p role="status" className="mt-8 rounded-2xl bg-lime/30 p-4 font-bold">{notice}</p>}<div className="mt-8"><label className="block"><span className="label">Search exercises</span><input type="search" placeholder="e.g. Bench Press" value={search} onChange={event=>setSearch(event.target.value)}/></label></div><div className="mt-8">{query.isLoading?<LoadingCards/>:query.error?<QueryError error={query.error} retry={()=>void query.refetch()}/>:query.data?.items.length===0?<div className="card text-center"><h2 className="text-2xl font-bold">No exercises yet</h2><p className="mt-2 text-moss">Add an exercise here or include one in your training log.</p></div>:items.length===0?<p className="card text-center text-moss">No exercises match “{search}”.</p>:<div className="grid gap-3 sm:grid-cols-2">{items.map(item=><NavLink key={item.id} to={`/exercises/${item.id}`} className="card group flex items-center justify-between"><span className="font-bold group-hover:underline">{item.name}</span><span aria-hidden="true">→</span></NavLink>)}</div>}</div></section>;
}

function ExerciseProgress({data}: {data:ExerciseStatistics}) {
  const hasStrength=data.series.some(item=>item.estimated_one_rep_max||item.top_load);
  const strength=data.series.map(item=>({date:formatShortDate(item.performed_on),e1rm:item.estimated_one_rep_max?Number(item.estimated_one_rep_max.value):null,topLoad:item.top_load?Number(item.top_load.value):null}));
  const work=data.series.map(item=>({date:formatShortDate(item.performed_on),volume:item.external_volume?Number(item.external_volume.value):null,reps:item.repetition_count}));
  const unit=data.summary.best_load?.unit??data.series.find(item=>item.top_load)?.top_load?.unit??"kg";
  const bestWork=data.summary.session_count===0?"—":data.summary.best_session_volume?formatVolume(data.summary.best_session_volume):`${data.summary.max_set_repetitions} reps`;
  return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="Sessions" value={String(data.summary.session_count)}/><MetricCard label="Best e1RM" value={formatMass(data.summary.best_estimated_one_rep_max)}/><MetricCard label="Top load" value={formatMass(data.summary.best_load)}/><MetricCard label={data.summary.best_session_volume?"Best volume":"Best set"} value={bestWork}/></div>{!hasStrength&&data.series.length>0&&<p className="rounded-2xl bg-white p-4 text-sm text-moss">This exercise has no loaded sets in the selected period. Strength estimates are unavailable, so progress is shown through repetitions and sets.</p>}{data.series.length===0?<div className="card text-center"><h2 className="text-2xl font-bold">No performances in this period</h2><p className="mt-2 text-moss">Choose a wider period to review earlier progress.</p></div>:<div className="grid gap-6 lg:grid-cols-2">{hasStrength&&<article className="card"><p className="eyebrow">Strength</p><h2 className="mt-1 text-2xl font-bold">Estimated 1RM and top load</h2><div className="mt-5 h-72" role="img" aria-label="Estimated one rep max and top load over time"><ResponsiveContainer width="100%" height="100%"><LineChart data={strength}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date"/><YAxis unit={` ${unit}`}/><Tooltip/><Legend/><Line type="monotone" dataKey="e1rm" name="Estimated 1RM" stroke="#25342d" strokeWidth={3} connectNulls/><Line type="monotone" dataKey="topLoad" name="Top load" stroke="#91b93e" strokeWidth={3} connectNulls/></LineChart></ResponsiveContainer></div><ul className="sr-only">{data.series.map(item=><li key={item.workout_id}>{formatDate(item.performed_on)}: e1RM {formatMass(item.estimated_one_rep_max)}, top load {formatMass(item.top_load)}</li>)}</ul></article>}<article className="card"><p className="eyebrow">Work</p><h2 className="mt-1 text-2xl font-bold">{hasStrength?"Volume and repetitions":"Repetitions per session"}</h2><div className="mt-5 h-72" role="img" aria-label="Training work over time"><ResponsiveContainer width="100%" height="100%"><BarChart data={work}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date"/><YAxis yAxisId="left" allowDecimals={false}/>{hasStrength&&<YAxis yAxisId="right" orientation="right"/>}<Tooltip/><Legend/>{hasStrength&&<Bar yAxisId="right" dataKey="volume" name={`Volume (${unit} · reps)`} fill="#25342d" radius={[7,7,0,0]}/>}<Bar yAxisId="left" dataKey="reps" name="Repetitions" fill="#91b93e" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></div><ul className="sr-only">{data.series.map(item=><li key={item.workout_id}>{formatDate(item.performed_on)}: {item.repetition_count} repetitions, volume {formatVolume(item.external_volume)}</li>)}</ul></article></div>}</div>;
}

export function ExerciseHistoryPage() {
  const {exerciseId=""}=useParams();const [period,setPeriod]=useState<StatisticsPeriod>("4w");
  const history=useInfiniteQuery({queryKey:["exercise-history",exerciseId,10],queryFn:({pageParam})=>historyApi.exerciseHistory(exerciseId,10,pageParam),initialPageParam:undefined as string|undefined,getNextPageParam:last=>last.next_cursor??undefined,enabled:!!exerciseId});
  const stats=useQuery({queryKey:["exercise-statistics",exerciseId,period],queryFn:()=>historyApi.exerciseStatistics(exerciseId,period),enabled:!!exerciseId});
  const items=history.data?.pages.flatMap(page=>page.items)??[];const exercise=stats.data?.exercise??history.data?.pages[0]?.exercise;
  return <section className="mx-auto max-w-6xl px-6 py-10"><div className="flex flex-wrap items-end justify-between gap-5"><PageHeader eyebrow="Exercise history" title={exercise?.name||"Exercise"} description="Progress metrics and every completed workout containing this exercise."/><PeriodSelector value={period} onChange={setPeriod}/></div><div className="mt-10">{stats.isLoading?<LoadingCards/>:stats.error?<QueryError error={stats.error} retry={()=>void stats.refetch()}/>:stats.data&&<ExerciseProgress data={stats.data}/>}</div><div className="mx-auto mt-12 max-w-4xl"><div className="mb-5"><p className="eyebrow">Complete log</p><h2 className="mt-1 text-2xl font-bold">Performance history</h2></div>{history.isLoading?<LoadingCards/>:history.error?<QueryError error={history.error} retry={()=>void history.refetch()}/>:items.length===0?<div className="card text-center"><h2 className="text-2xl font-bold">No completed performances</h2><p className="mt-2 text-moss">This exercise has no completed workout history yet.</p></div>:<div className="grid gap-5">{items.map(item=><article key={item.workout_id} className="card"><p className="eyebrow">{formatDate(item.performed_on)}</p>{item.workout_notes&&<p className="mt-2 text-sm text-moss">{item.workout_notes}</p>}<div className="mt-5 space-y-5">{item.occurrences.map(occurrence=><section key={occurrence.id}>{occurrence.notes&&<p className="text-sm text-moss">{occurrence.notes}</p>}<Sets occurrence={occurrence}/></section>)}</div></article>)}{history.hasNextPage&&<button className="button-secondary mx-auto mt-2" disabled={history.isFetchingNextPage} onClick={()=>void history.fetchNextPage()}>{history.isFetchingNextPage?"Loading…":"Load more"}</button>}</div>}</div></section>;
}
